#!/usr/bin/env python3
"""
Pre-rasterize a TrueType font into a grayscale atlas the kernel can
alpha-blend onto the framebuffer. The output is a single C header
embedded into the kernel image; we don't need a runtime font engine.

Usage:
    tools/gen_font.py <ttf-path> > src/font_smooth.h

Produces two faces (UI 16 px and Heading 24 px) covering ASCII
0x20..0x7e plus a U+2022 bullet.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

CHARS = [chr(c) for c in range(0x20, 0x7f)]
SIZES = [("ui", 16), ("hd", 24)]

def rasterize(font_path, px):
    """Render each glyph into its own PIL image and pack the alpha
    bytes into one big atlas, recording offsets per glyph."""
    font = ImageFont.truetype(font_path, px)
    glyphs = []
    bitmap = bytearray()
    line_height = 0
    # We render with a fixed scratch canvas big enough for any glyph
    # at this size, then crop tightly.
    canvas_w = px * 2 + 4
    canvas_h = px * 2 + 4
    for ch in CHARS:
        img = Image.new('L', (canvas_w, canvas_h), 0)
        draw = ImageDraw.Draw(img)
        # Draw at offset (px/2, px/2) so glyphs that have negative
        # bearings still fit in the canvas.
        origin_x, origin_y = px // 2, px // 2
        draw.text((origin_x, origin_y), ch, fill=255, font=font)
        # Find tight bbox of non-zero pixels
        bbox = img.getbbox()
        if bbox is None:
            w, h = 0, 0
            bx, by = 0, 0
            data = b''
        else:
            x0, y0, x1, y1 = bbox
            cropped = img.crop(bbox)
            w, h = cropped.size
            bx = x0 - origin_x
            by = y0 - origin_y
            data = cropped.tobytes()
        adv = int(round(font.getlength(ch)))
        if h > line_height:
            line_height = h
        offset = len(bitmap)
        if data:
            bitmap.extend(data)
        glyphs.append((ch, w, h, bx, by, adv, offset))
    return glyphs, bytes(bitmap), line_height

def emit(font_path):
    out = []
    out.append("/* Auto-generated by tools/gen_font.py. Do not hand-edit. */")
    out.append("#ifndef HOBBY_OS_FONT_SMOOTH_H")
    out.append("#define HOBBY_OS_FONT_SMOOTH_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("struct smooth_glyph {")
    out.append("    uint8_t  w, h;")
    out.append("    int8_t   bearing_x;")
    out.append("    int8_t   bearing_y;   /* top-of-bbox offset from baseline */")
    out.append("    uint8_t  advance;")
    out.append("    uint8_t  pad;")
    out.append("    uint32_t bitmap_offset;")
    out.append("};")
    out.append("")
    for tag, px in SIZES:
        glyphs, bitmap, lh = rasterize(font_path, px)
        ascent = max(g[4] for g in glyphs) or 0
        out.append(f"#define SMOOTH_FONT_{tag.upper()}_LINE_HEIGHT {lh}")
        out.append(f"#define SMOOTH_FONT_{tag.upper()}_ASCENT {ascent}")
        out.append(f"static const uint8_t smooth_font_{tag}_bitmap[{len(bitmap)}] = {{")
        # 16 bytes per line
        line = []
        for i, b in enumerate(bitmap):
            line.append(f"0x{b:02x}")
            if (i + 1) % 16 == 0:
                out.append("    " + ", ".join(line) + ",")
                line = []
        if line:
            out.append("    " + ", ".join(line))
        out.append("};")
        out.append(f"static const struct smooth_glyph smooth_font_{tag}_glyphs[{len(glyphs)}] = {{")
        for ch, w, h, bx, by, adv, offset in glyphs:
            comment = ch if ch not in ('\\', '/', '*') else '?'
            out.append(f"    {{ {w}, {h}, {bx}, {by}, {adv}, 0, {offset} }},  /* '{comment}' */")
        out.append("};")
        out.append("")
    out.append("#endif")
    out.append("")
    return "\n".join(out)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("usage: gen_font.py <ttf-path>", file=sys.stderr)
        sys.exit(64)
    sys.stdout.write(emit(sys.argv[1]))
